check-upstream.sh
Checks if there is a new upstream version for each overlay packages.
The current output:
```
New version upstream: extlib.1.7.6
New version upstream: fmt.0.8.6
New version upstream: psq.0.1.1
New version upstream: tls.0.10.2
New version upstream: uuidm.0.9.7
```
The script requires an opam installation with the default and the overlays repositories up to date.
It takes the name of the overlays repository as argument.
=> Add the check-upstream.sh script

packages/fmt/fmt.0.8.6+dune/opam
I just pushed the port [here](https://github.com/dune-universe/fmt/commit/0522ff405f207af1f79bda66700546bf468ef236).
The previous port used jbuilder so I updated it a bit and removed `topkg` files to keep things clean.
I didn't actually handle the depopts which makes me wonder about how `duniverse` currently handle those. I'm guessing it won't pull them in, meaning the project won't build so I might need to fix that before we merge this PR.
=> Release fmt.0.8.6 dune port

packages/logs/logs.0.6.3+dune/opam
PR on opam: https://github.com/ocaml/opam-repository/pull/13991
I pushed directly to https://github.com/dune-universe/logs/tree/duniverse-v0.6.3.
Note that `opam install logs` will fail because dune will try to build libraries that depend on optional dependencies.
=> logs.0.6.3+dune

packages/ocamlfind/ocamlfind.1.8.0+dune/opam
We've been having issues with ocamlfind in `duniverse` recently (see https://github.com/avsm/duniverse/pull/14#issuecomment-484426225) so I thought that might help.
Just took the port from https://github.com/dune-universe/lib-findlib/tree/duniverse-1.8.0.
=> Release @avsm's dune port of ocamlfind

packages/cmdliner/cmdliner.1.0.4+dune/opam
(this overlay is needed to add dune to the build deps in opam)
=> cmdliner 1.0.4: also use upstream tarball since it includes dune files

README.md
Since duniverse now pins source dependencies to a commit, it doesn't hurt build reproducibity for duniverse users while making it easier to improve or fix existing dune ports.
=> Encourage the use of branch over tag for dune ports

packages/ocamlfind/ocamlfind.1.8.1+dune/opam
It appears there is some kind of hack in here and `ocamlfind` and `findlib` are split, the former depending on the latter.
This updates the `ocamlfind` package in response to #42 !
=> Add ocamlfind 1.8.1

packages/seq/seq.0.1+dune/opam, packages/seq/seq.base+dune/opam
This ports the `seq` compatibility package to `dune` so that it works well within a duniverse.
You can take a look [here](https://github.com/dune-universe/seq/commit/8feae7e02820f656c6c2ebe5a126b20d3eecb76e). Having conditional actions would be great but unfortunately we have to without it for now.
=> Add a seq 0.1 dune port

packages/uchar/uchar.0.0.2+dune/opam
The virtual package worked for opam-monorepo but trying to opam install the generated lockfiles would fail because uchar.0.0.2+dune wasn't pinned since it had no sources and doesn't exist outside opam-overlays.
=> Turn uchar into a dummy package that will satisfy both opam-monorepo and opam

packages/opam-file-format/opam-file-format.2.1.0+dune/opam
opam-file-format has a depopts on dune which doesn't satisfy opam-monorepo's build system detection logic. We should probably
consider a better way to detect the build system, maybe using the `build` field from the opam file but that wouldn't have necessarily
worked here either. A specific field in the opam file with the list of supported build systems would be great but in the meantime this port does the job.
=> Add dune port of opam-file-format 2.1.0

.drone.yml, list-overrides.sh, packages/asetmap/asetmap.0.8.1+dune/opam
First step for https://github.com/dune-universe/opam-overlays/issues/73 
So I have a script to automate the process, but I want to be sure that it works for a single package beforehand. 
Basically for each package that have a git url, it makes a tag on the corresponding branch with the version number (`vxxx+dune`) and push it, then fetches the resulting archive to compute the SHA256 (that is used for caching) and finally updates opam overlays.
I'm not sure about the last steps, as maybe it's more robust to make a proper github release, but I had troubles automating the `dune-release` process as it does a lot of magic.
=> Use tarball as src for asetmap

.drone.yml, list-overrides.sh
By having two different versions in opam-overlays, `opam-file-format` breaks the CI in the following PR https://github.com/dune-universe/opam-overlays/pull/72.
The drone script tries to install every opam-overlays package at once, but fails because it can't satisfy the constraints (two different versions of `opam-file-format`). I added an option in `list-overrides.sh` to select the last version when several are available.
=> When having multiple packages, CI tests last version

packages/inotify/inotify.2.3.0+dune/opam
For a project using `opam monorepo`, inotify is needed. As it currently doesn't support `dune` and rely on oasis, this PR intends to offer a version working with `dune` while waiting for a merge in the official repository.
=> inotify: 2.3.0

packages/dum/dum.1.0.1+dune/opam
This should conclude work on `dum` basically forever since there is only one release of it and it is not maintained actively.
=> Add `dum.1.0.1+dune`

packages/fmt/fmt.0.8.10+dune/opam
OCaml Format pretty-printer combinators
- Project page: <a href="https://github.com/dune-universe/fmt">https://github.com/dune-universe/fmt</a>
- Documentation: <a href="https://github.com/dune-universe/fmt">https://github.com/dune-universe/fmt</a>
* Require OCaml >= 4.08. This drops the dependency on the
`stdlib-shims` and `seq` packages.
* Add the `[@@ocaml.deprecated]` annotation to deprecated
functions. Thanks to Antonin Décimo for the patch.
=> [new release] fmt (0.8.10+dune)

packages/mtime/mtime.1.3.0+dune/opam
Monotonic wall-clock time for OCaml
- Project page: <a href="https://github.com/dune-universe/mtime">https://github.com/dune-universe/mtime</a>
* Add Windows support. Thanks to Andreas Hauptmann for the patch
and Corentin Leruth for the integration.
=> [new release] mtime (1.3.0+dune)

README.md
The merged repository is not updated anymore, people should use `opam-repository` along with opam-overlays.
We should consider formalizing the state of versions in opam-overlays. But I guess we should have a meeting about this first and agree what the way forward on it is.
=> Update wording on the readme

packages/fmt/fmt.0.9.0+dune/opam
OCaml Format pretty-printer combinators
- Project page: <a href="https://github.com/dune-universe/fmt">https://github.com/dune-universe/fmt</a>
* Require OCaml >= 4.08. This drops the dependency on the
`stdlib-shims` and `seq` packages.
* Add the `[@@ocaml.deprecated]` annotation to deprecated
functions. Thanks to Antonin Décimo for the patch.
=> [new release] fmt (0.9.0+dune)

packages/ptime/ptime.1.0.0+dune/opam
POSIX time for OCaml
- Project page: <a href="https://github.com/dune-universe/ptime">https://github.com/dune-universe/ptime</a>
* Change the `js_of_ocaml` strategy for `Ptime_clock`'s JavaScript
implementation. Primitives of `ptime.clock.os` are now implemented
in pure JavaScript and linked by `js_of_ocaml`. This means that the
`ptime.clock.jsoo` library no longer exists, simply link against
`ptime.clock.os` instead. Thanks to Hugo Heuzard for suggesting and
implementing this.
* Require OCaml >= 4.08
* Correct a potential overflow in Ptime.Span.of_float_s (dune-universe/ptime#26).
=> [new release] ptime (1.0.0+dune)

packages/dose3/dose3.5.0.1+dune/opam
I've been investigating getting a newer opam to install in the monorepo, and opam 2.1.2 requires dose3 that is `>5` and `<6`. We have that in the repo, no problem. Unfortunately, our dose3 port does not currently work, because it depends on ocamlgraph and ocamlgraph 2.0.0 added a change
```
The value `empty' is required but not provided
```
Hence we need to make sure our old dose3 version does not pick up ocamlgraph >= 2.0.0, hence this PR.
=> Set maximum version of ocamlgraph for dose3

packages/ptime/ptime.1.0.0+dune2/opam
POSIX time for OCaml
- Project page: <a href="https://github.com/dune-universe/ptime">https://github.com/dune-universe/ptime</a>
* Change the `js_of_ocaml` strategy for `Ptime_clock`'s JavaScript
implementation. Primitives of `ptime.clock.os` are now implemented
in pure JavaScript and linked by `js_of_ocaml`. This means that the
`ptime.clock.jsoo` library no longer exists, simply link against
`ptime.clock.os` instead. Thanks to Hugo Heuzard for suggesting and
implementing this.
* Require OCaml >= 4.08
* Correct a potential overflow in Ptime.Span.of_float_s (dune-universe/ptime#26).
=> [new release] ptime (1.0.0+dune2)

README.md
In the light of our recent work on updating or releasing new ports, it's become clear that this needs more control.
The process described in this PR should help get good confidence in the ports by submitting them through a regular PR review process at the port level along with the release PR.
Enabling `ocaml-ci` on the `dune-universe` forks and have it run on those PRs should also help us get confidence in the quality of the ports.
=> Document the new, improved port process

packages/mtime/mtime.1.4.0+dune/opam
Monotonic wall-clock time for OCaml
- Project page: <a href="https://github.com/dune-universe/mtime">https://github.com/dune-universe/mtime</a>
* Change the `js_of_ocaml` strategy for `Mtime_clock`'s JavaScript
implementation. Primitives of `mtime.clock.os` are now implemented
in pure JavaScript and linked by `js_of_ocaml`.  This means that the
`mtime.clock.jsoo` library no longer exists, simply link against
`mtime.clock.os` instead. Thanks to Hugo Heuzard for suggesting and
implementing this.
* Add `Mtime.{min,max}_stamp`.
* Add durations `Mtime.Span.{ns,us,ms,s,min,hour,day,year}` and
the `Mtime.Span.(*)` operator (dune-universe/mtime#28).
* Deprecate `Mtime.s_to_*` and `Mtime.*_to_s` floating point constants (dune-universe/mtime#28).
* Require OCaml >= 4.08.
* Allow compiling with MSVC …
=> [new release] mtime (1.4.0+dune)

packages/rresult/rresult.0.7.0+dune/opam
Result value combinators for OCaml
- Project page: <a href="https://github.com/dune-universe/rresult">https://github.com/dune-universe/rresult</a>
* Require OCaml >= 4.08. This drops the dependency on the `result`
compatibility package.
* Users are encouraged to move the the `Stdlib.Result` module
available in OCaml 4.08.
=> [new release] rresult (0.7.0+dune)

packages/cmdliner/cmdliner.1.1.0+dune/opam
The changes were absolutely minimal because cmdliner already comes with `dune` (1.4) files, so it was essentially just using it in the opam file.
Potentially we could drop the port itself and just ship a modified opam-file in opam-overlays. What do you think @NathanReb?
=> [new release] Cmdliner.1.1.0+dune

packages/uutf/uutf.1.0.3+dune/opam
Non-blocking streaming Unicode codec for OCaml
- Project page: <a href="https://github.com/dune-universe/uutf">https://github.com/dune-universe/uutf</a>
- Support for OCaml 5.00, thanks to Kate (@kit-ty-kate) for
the patch.
=> [new release] uutf (1.0.3+dune)

packages/uuidm/uuidm.0.9.8+dune/opam
Universally unique identifiers (UUIDs) for OCaml
- Project page: <a href="https://github.com/dune-universe/uuidm">https://github.com/dune-universe/uuidm</a>
- Add deprecation warnings on what is already deprecated.
- Require OCaml 4.08 and support 5.00 (Thanks to Kate @ki-ty-kate
for the patch).
=> [new release] uuidm (0.9.8+dune)

packages/uucp/uucp.14.0.0+dune/opam
Unicode character properties for OCaml
- Project page: <a href="https://github.com/dune-universe/uucp">https://github.com/dune-universe/uucp</a>
- Unicode 14.0.0 support.
- Tweak `Uucp.Break.tty_width_hint` (09d2186). Thanks to David Kaloper
Meršinjak.
=> [new release] uucp (14.0.0+dune)

packages/bheap/bheap.1.0.0+dune/opam, packages/ppx_tools/ppx_tools.6.1+dev+dune/opam
Github is turning off unencrypted git protocol which prevents us from running things like `ls-remote` using those URLs.
See: https://github.blog/2021-09-01-improving-git-protocol-security-github/
This works perfectly well over https though hence the rewriting of those URLs.
=> Switch URLs from `git://` to `git+https://` for github

packages/stdcompat/stdcompat.17+dune/opam
This adds `stdcompat` but instead of using `make` it uses the dune files that are in the repository and the original tarball.
Closes #86
=> Add `stdcompat` `17+dune`

packages/stdcompat/stdcompat.18+dune/opam
This adds stdcompat v18, as `stdcompat.18` (to mirror the way OPAM versions it).
=> [new release] `stdcompat.18`

packages/hacl-star-raw/hacl-star-raw.0.4.5+dune/opam, packages/hacl-star/hacl-star.0.4.5+dune/opam
OCaml API for EverCrypt/HACL*
- Project page: <a href="http://github.com/dune-universe/hacl-star-dune">http://github.com/dune-universe/hacl-star-dune</a>
=> [new release] hacl-star and hacl-star-raw (0.4.5+dune)

packages/ocp-ocamlres/ocp-ocamlres.0.4+dune2/opam
A simple tool and library to embed files and directories inside an OCaml executables
- Project page: <a href="http://github.com/dune-universe/ocp-ocamlres">http://github.com/dune-universe/ocp-ocamlres</a>
=> [new release] ocp-ocamlres (0.4+dune2)

packages/ctypes-foreign/ctypes-foreign.0.20.1+dune/opam, packages/ctypes/ctypes.0.20.1+dune/opam
Combinators for binding to C libraries without writing any C
- Project page: <a href="https://github.com/dune-universe/ocaml-ctypes">https://github.com/dune-universe/ocaml-ctypes</a>
* Fix warning 9 [missing-record-field-pattern] in generated OCaml code
https://github.com/ocamllabs/ocaml-ctypes/pull/700
Thanks to Antonin Décimo (@MisterDA) for contributing to this release.
=> [new release] ctypes and ctypes-foreign (0.20.1+dune)

packages/num/num.1.4+dune2/opam
This hopefully fixes the dependency problems by bringing the 1.4 dune build closer to the upstream dune port.
=> [new release] num.1.4+dune2

packages/base-bytes/base-bytes.base+dune/opam
Fixed upstream https://github.com/kit-ty-kate/bytes/pull/1 and backported here.
Fixes https://github.com/tarides/opam-monorepo/issues/343
=> Fix the package name to be `bytes`

packages/base-bytes/base-bytes.base+dune/opam
Reported by @avsm in https://github.com/dune-universe/opam-overlays/pull/175#issuecomment-1376678278, this makes sure the `base-bytes` polyfill is only picked on OCaml 5.0.
CC @kit-ty-kate.
=> Restrict `base-bytes` to only be selected on OCaml >= 5.0

packages/base-bytes/base-bytes.base+dune/opam
This reverts commit b2b5e7e56d1a30cdd24a04504b88e24d88cef101.
For unbreaking compiling MirageOS unikernels.
=> Revert "Restrict `base-bytes` to only be selected on OCaml >= 5.0"

packages/findlib/findlib.1.9.5+dune/opam, packages/ocamlfind/ocamlfind.1.9.5+dune/opam
A library manager for OCaml
- Project page: <a href="https://github.com/dune-universe/lib-findlib">https://github.com/dune-universe/lib-findlib</a>
=> [new release] ocamlfind and findlib (1.9.5+dune)

packages/ptime/ptime.1.1.0+dune/opam
POSIX time for OCaml
- Project page: <a href="https://github.com/dune-universe/ptime">https://github.com/dune-universe/ptime</a>
- `Ptime.of_rfc3339` timezone offset parsing. Be even more lenient
in non-strict parsing mode: allow `hhmm` and `hh` timezone offsets.
(strict is `hh:mm`). Allows to parse an even larger subset of
ISO 8601 than RFC 3339 (dune-universe/ptime#31).
- Add `Ptime.{to,of}_year`. Less costly than extracting the first
component of `Ptime.to_date_time`. Useful for example to find
out which DST rules a timestamp is subjected to for rendering.
- Add `?tz_offset_s` optional argument to `Ptime.{of,to}_date` (dune-universe/ptime#32).
- Add `Ptime.weekday_num`. An integer is often more convenient
than the enum value of `Ptime.weekday` (dune-universe/ptime#30).
- Add …
=> [new release] ptime (1.1.0+dune)

packages/uunf/uunf.15.0.0+dune/opam
Unicode text normalization for OCaml
- Project page: <a href="https://github.com/dune-universe/uunf">https://github.com/dune-universe/uunf</a>
- Unicode 15.0.0 support.
=> [new release] uunf (15.0.0+dune)

packages/base-bytes/base-bytes.base+dune/opam
=> Add `post-message` about installing base-bytes into a switch

packages/carton-git/carton-git.0.7.0+overlay/opam, packages/carton-lwt/carton-lwt.0.7.0+overlay/opam, packages/carton/carton.0.7.0+overlay/opam
with this, I hope to finally being able to use git 3.14 in a unikernel, with "opam-monorepo 0.4.0".
//cc @samoht #197
=> add carton 0.7.0, using the git 3.14 tarball

packages/uuseg/uuseg.15.1.0+dune/opam
Unicode text segmentation for OCaml
- Project page: <a href="https://github.com/dune-universe/uuseg">https://github.com/dune-universe/uuseg</a>
- Unicode 15.1.0 support.
- Requires OCaml 4.14.0 for the UTF decoders.
- The `Uuseg_string` module was rewritten to use the standard library
UTF decoders and was moved to the `uuseg` library. The `uuseg.string`
library is deprecated, it warns on usage and simply requires `uuseg`.
- The sample code was rewritten to use the standard library UTF
decoders.
=> [new release] uuseg (15.1.0+dune)

packages/uunf/uunf.15.1.0+dune/opam
Unicode text normalization for OCaml
- Project page: <a href="https://github.com/dune-universe/uunf">https://github.com/dune-universe/uunf</a>
- Unicode 15.1.0 support.
- Requires OCaml 4.14.0.
- The `Uunf_string` module was rewritten to use the standard library
UTF decoders and was moved to the `uunf` library. The `uunf.string`
library is deprecated, it warns on usage and simply requires `uunf`.
- The sample code was rewritten to use the standard library UTF
decoders.
=> [new release] uunf (15.1.0+dune)

packages/uucp/uucp.15.1.0+dune/opam
Unicode character properties for OCaml
- Project page: <a href="https://github.com/dune-universe/uucp">https://github.com/dune-universe/uucp</a>
- Unicode 15.1.0 support.
- Require OCaml 4.14.0.
- Use module aliases for the property modules. Only pay for the
modules you use (dune-universe/uucp#2).
- Use the standard library UTF decoders in the sample code and in
`ucharinfo` (dune-universe/uucp#23).
- The `Num.numeric_value` had to be changed to accomodate for the
data. It now returns either NaN or a list of numbers. This is due to
the interpretation of U+5146 and U+79ED which is locale dependent
and thus can represent multiple values. In all other cases you
should get singelton lists so far.
- Rename `Uucd.Cjk.ids_bin_op` to `Uucd.Cjk.ids_binary_operator`.
- Rename `Uucd.Cjk.ids_tri_op` …
=> [new release] uucp (15.1.0+dune)

packages/cmdliner/cmdliner.1.2.0+dune/opam
Declarative definition of command line interfaces for OCaml
- Project page: <a href="https://github.com/dune-universe/cmdliner">https://github.com/dune-universe/cmdliner</a>
- In manpage specification the new variable `$(iname)` substitutes the
command invocation (from program name to subcommand) in bold (dune-universe/cmdliner#168).
This variable is now used in the default introduction of the `EXIT STATUS`
section. Thanks to Ali Caglayan for suggesting.
- Fix manpage rendering when `PAGER=less` is set (dune-universe/cmdliner#167).
- Plain text manpage rendering: fix broken handling of `` `Noblank ``.
Thanks to Michael Richards and Reynir Björnsson for the report (dune-universe/cmdliner#176).
- Fix install to directory with spaces (dune-universe/cmdliner#172). Thanks to
@ZSFactory for …
=> [new release] cmdliner (1.2.0+dune)

packages/colombe/colombe.0.8.0+overlay/opam, packages/sendmail-lwt/sendmail-lwt.0.8.0+overlay/opam, packages/sendmail/sendmail.0.8.0+overlay/opam
/cc @hannesm to fix the issue that `opam monorepo` should not pick the the same Git repository between `received` and `colombe` (they don't have the same release cycle).
=> Add an overlay suffix for the colombe distribution

packages/carton-git/carton-git.0.7.1+overlay/opam, packages/carton-lwt/carton-lwt.0.7.1+overlay/opam, packages/carton/carton.0.7.1+overlay/opam
this is still required to use git 3.15 in a unikernel... /cc @dinosaure @samoht
=> add cartion 0.7.1 to use the git 3.15 tarball

packages/lwt_ppx/lwt_ppx.2.1.0+lwt.5.7.0/opam
Add the `lwt_ppx` 2.1.0 bundled with `lwt` 5.7.0 so that `monorepo` can find a common revision for both packages that is compatible with OCaml 5.2.
=> Package the `lwt_ppx` 2.1.0 bundled with `lwt` 5.7.0

packages/received/received.0.8.1+overlay/opam
Again, this package is needed due to the colombe distribution which contains 2 packages, `colombe` and `received` and they don't have the same release cycle.
=> Add received.0.8.1+overlays to let opam-monorepo to download the last version of colombe

.github/workflows/ci.yml, packages/cmdliner/cmdliner.1.3.0+dune/opam, test/irmin.t/run.t, test/mdx.t/dune, test/mdx.t/run.t
Declarative definition of command line interfaces for OCaml
- Project page: <a href="https://github.com/dune-universe/cmdliner">https://github.com/dune-universe/cmdliner</a>
- Add let operators in `Cmdliner.Term.Syntax` (dune-universe/cmdliner#173). Thanks to Benoit
Montagu for suggesting, Gabriel Scherer for reminding us of language
punning obscurities and Sebastien Mondet for strengthening the case
to add them.
- Pager. Support full path command lookups on Windows.
(dune-universe/cmdliner#185). Thanks to @kit-ty-kate for the report.
- In manpage specifications use `$(iname)` in the default
introduction of the `ENVIRONMENT` section. Follow up to
dune-universe/cmdliner#168.
- Add `Cmd.eval_value'` a variation on `Cmd.eval_value`.
=> [new release] cmdliner (1.3.0+dune)

packages/ptime/ptime.1.2.0+dune/opam
POSIX time for OCaml
- Project page: <a href="https://github.com/dune-universe/ptime">https://github.com/dune-universe/ptime</a>
- Fix fractional renderings of `Ptime.Span.pp` with leading zeros. For
example 1.036s would render as 1.36s. This is a *rendering* bug in a
function for human display, not a bug in the computations or
conversion functions of `Ptime`.
- Add `Ptime.weekday` type for naming the result of the `Ptime.weekday`
function.
- Regularize naming structure. The `ptime.clock.os` library is deprecated.
Use `ptime.clock` instead.
- Make the library `ptime.clock` export `ptime`.
=> [new release] ptime (1.2.0+dune)

packages/uuseg/uuseg.15.1.0+dune2/opam
Unicode text segmentation for OCaml
- Project page: <a href="https://github.com/dune-universe/uuseg">https://github.com/dune-universe/uuseg</a>
- Unicode 15.1.0 support.
- Requires OCaml 4.14.0 for the UTF decoders.
- The `Uuseg_string` module was rewritten to use the standard library
UTF decoders and was moved to the `uuseg` library. The `uuseg.string`
library is deprecated, it warns on usage and simply requires `uuseg`.
- The sample code was rewritten to use the standard library UTF
decoders.
Fixes #213
=> [new release] uuseg (15.1.0+dune2)

packages/logs/logs.0.9.0+dune/opam
Logging infrastructure for OCaml
- Project page: <a href="https://erratique.ch/software/logs">https://erratique.ch/software/logs</a>
- Documentation: <a href="https://erratique.ch/software/logs/doc">https://erratique.ch/software/logs/doc</a>
* Replace references and mutable fields by atomic references to avoid
race conditions (dune-universe/logs#56). Thanks to Nathan Taylor for reporting.
* Fix `Logs.{err,warn}_count`. The counts were counting the reports
not the logs which is not what the spec says. This means the counts
were wrong when the reporting level was below the corresponding
level (dune-universe/logs#55). Thanks to Mathieu Barbin for the report.
* Fix `Log.Tag.list` always returning the empty list.
* `Logs.format_reporter` and `Logs_fmt.reporter` replace a few format
strings and …
=> [new release] logs (0.9.0+dune)

packages/cmdliner/cmdliner.2.0.0+dune/opam
Declarative definition of command line interfaces for OCaml
- Project page: <a href="https://github.com/dune-universe/cmdliner">https://github.com/dune-universe/cmdliner</a>
- **IMPORTANT** Cmdliner no longer allows command names, option names,
and `Arg.enum` values to be specified by a prefix if the prefix is
unambiguous. See dune-universe/cmdliner#200 for the rationale. To quickly salvage scripts
that may be relying on the old behaviour, it can be restored by
setting the environment variable `CMDLINER_LEGACY_PREFIXES=true`.
However the scripts should be fixed: this escape hatch will be
removed in the future.
- Pager. If set, respect the user's `LESS` environment variable
(otherwise the default `LESS=FRX` is left unchanged).  Note however
that you likely need at least `R` specified if …
=> [new release] cmdliner (2.0.0+dune)
