packages/fmt/fmt.0.8.6+dune/opam
This was pretty bad on my side but I think it showcases how bad we need a CI here!
=> Fix fmt.0.8.6+dune

packages/ocamlfind/ocamlfind.1.8.0+dune/opam
=> Fix ocamlfind.1.8.0+dune's opam file

packages/reactiveData/reactiveData.0.2.2+dune/opam
=> Update reactiveData to track upstream until release of version 0.2.3

packages/ctypes/ctypes.0.14.0+dune/opam
Haven't touched `opam-overlays` in a while so a double check would be nice!
=> Add dunified ctypes

packages/conduit-async/conduit-async.1.5.0+dune/opam, packages/conduit-lwt-unix/conduit-lwt-unix.1.5.0+dune/opam, packages/conduit-lwt/conduit-lwt.1.5.0+dune/opam, packages/conduit/conduit.1.5.0+dune/opam, packages/mirage-conduit/mirage-conduit.3.2.0+dune/opam
=> switch conduit packages to dune-universe forks

packages/charInfo_width/charInfo_width.1.1.0+dune/opam
there is no actual changes here, but this mirror is a convenience
until we fix avsm/duniverse#61 and support Mercurial dev repos
=> add a mirror of charInfo_width using git

packages/merlin/merlin.3.3.4+dune/opam
upstream at https://github.com/ocaml/merlin/pull/1143
=> add fork of merlin to work in release mode

packages/num/num.1.3+dune/opam
The build system rules have been patched to support cross-compilation:
https://github.com/dune-universe/num/pull/1
=> fix num 1.3

packages/fpath/fpath.0.7.3+dune/opam
This release add support for OCaml 4.12
=> Fpath: add version 0.7.3

packages/inotify/inotify.2.3.0+dune/opam
I realize that I introduce a typo in the `inotify` so this PR is here to correct this!
Sorry about that...
=> fix inotify typo

packages/bos/bos.0.2.1+dune/opam
Fixes #88.
This was based on the previous port. I tested it on opam-monorepo and everything built fine!
=> Add bos.0.2.1 to overlays

packages/inotify/inotify.2.3.0+dune/opam
Hi,
I have moved my forks to another repo. I update the links to avoid crashes when GitHub will not redirect them anymore.
=> inotify: update links

.github/workflows/lint.yml
This PR will have a github action running the linter. It will probably take a few tries to see it working.
=> Run linter on changes in PRs

packages/dum/dum.1.0.1+dune2/opam
Inspect the runtime representation of arbitrary OCaml values
- Project page: <a href="https://github.com/dune-universe/dum">https://github.com/dune-universe/dum</a>
=> [new release] dum (1.0.1+dune2)

packages/logs/logs.0.7.0+dune2/opam
As it says on the can :) Thanks to the report by @patricoferris.
=> logs 0.7.0+dune2: Fixed the result dependency

packages/camlzip/camlzip.1.11+dune/opam, packages/zip/zip.1.11+dune/opam
Accessing compressed files in ZIP, GZIP and JAR format.
- Project page: <a href="https://github.com/dune-universe/camlzip">https://github.com/dune-universe/camlzip</a>
=> [new release] zip and camlzip (1.11+dune)

packages/xmlm/xmlm.1.4.0+dune/opam
Update of xmlm.1.3.0+dune port
=> [new release] xmlm.1.4.0+dune

packages/hmap/hmap.0.8.1+dune/opam
Hmap provides heterogeneous value maps for OCaml
- Project page: <a href="https://github.com/dune-universe/hmap">https://github.com/dune-universe/hmap</a>
First release.
=> [new release] hmap (0.8.1+dune)

packages/uchar/uchar.0.0.2+dune/opam, packages/uchar/uchar.0.0.2+dune2/opam
Dummy but non virtual package to satisfy both opam-monorepo and opam
- Project page: <a href="https://github.com/dune-universe/uchar">https://github.com/dune-universe/uchar</a>
=> [new release] uchar (0.0.2+dune2)

packages/uuseg/uuseg.14.0.0+dune/opam
Dune port of uuseg. Mostly forward porting changes and updating to upstream changes.
Closes #95
=> [new release] uuseg 14.0.0

packages/zarith/zarith.1.12+dune/opam
Implements arithmetic and logical operations over arbitrary-precision integers
- Project page: <a href="https://github.com/dune-universe/Zarith">https://github.com/dune-universe/Zarith</a>
* Dune port for Zarith 1.12
=> [new release] zarith (1.12+dune)

packages/ocp-ocamlres/ocp-ocamlres.0.4+dune/opam
A simple tool and library to embed files and directories inside an OCaml executables
- Project page: <a href="http://github.com/dune-universe/ocp-ocamlres">http://github.com/dune-universe/ocp-ocamlres</a>
=> [new release] ocp-ocamlres (0.4+dune)

packages/hacl-star-raw/hacl-star-raw.0.4.5+dune/opam, packages/hacl-star/hacl-star.0.4.5+dune/opam
OCaml API for EverCrypt/HACL*
- Project page: <a href="http://github.com/dune-universe/hacl-star-dune">http://github.com/dune-universe/hacl-star-dune</a>
=> [new release] hacl-star and hacl-star-raw (0.4.5+dune)

packages/pringo/pringo.1.3+dune/opam
Pseudo-random, splittable number generators
- Project page: <a href="https://github.com/dune-universe/pringo">https://github.com/dune-universe/pringo</a>
=> [new release] pringo (1.3+dune)

packages/hacl-star-raw/hacl-star-raw.0.4.5+dune2/opam, packages/hacl-star/hacl-star.0.4.5+dune2/opam
OCaml API for EverCrypt/HACL*
- Project page: <a href="http://github.com/dune-universe/hacl-star-dune">http://github.com/dune-universe/hacl-star-dune</a>
- Faster fallback implementations for certain intrinsics, leading to improved
performance, notably on ARMv8
=> [new release] hacl-star and hacl-star-raw (0.4.5+dune2)

packages/num/num.1.4+dune/opam
This is just the original 1.4 release with updated metadata to build with dune.
=> Release num.1.4+dune

packages/stdcompat/stdcompat.18+dune3/opam
This adds some more fixes for the stdcompat port.
=> [new release] stdcompat.18+dune3

packages/mtime/mtime.1.4.0+dune2/opam
This release adds the fixes by @patricoferris in https://github.com/dune-universe/mtime/pull/2
=> `mtime.1.4+dune2` revised release

.github/workflows/lint.yml
Seems like it needs `ocaml-compiler` now or it will fail.
=> Supply `ocaml-compiler` to `setup-ocaml`

packages/batteries/batteries.3.6.0+dune/opam
A community-maintained standard library extension
- Project page: <a href="https://github.com/dune-universe/batteries-included">https://github.com/dune-universe/batteries-included</a>
=> [new release] batteries (3.6.0+dune)

packages/inifiles/inifiles.1.2+dune/opam
An ini file parser
- Project page: <a href="https://github.com/dune-universe/ocaml-inifiles">https://github.com/dune-universe/ocaml-inifiles</a>
=> [new release] inifiles (1.2+dune)

packages/uucp/uucp.15.0.0+dune/opam
Unicode character properties for OCaml
- Project page: <a href="https://github.com/dune-universe/uucp">https://github.com/dune-universe/uucp</a>
- Unicode 15.0.0 support.
- Tool `ucharinfo`: allow to query more than one character at a time.
- Tool `ucharinfo`: tool allow to search characters by name.
=> [new release] uucp (15.0.0+dune)

README.md
Old one does not seem to be working anymore
=> Fix link for `opam-monorepo` plugin

packages/brr/brr.0.0.3+dune/opam
=> [new release] brr (0.0.3+dune)

packages/note/note.0.0.2+dune/opam
/cc @NathanReb & @Leonidas-from-XIV
=> [new release] note (0.0.2+dune)
